[workspace]
resolver = "2"
members = ["crates/ble", "crates/utils", "crates/macros"]
default-members = ["crates/ble"]

[workspace.dependencies]
utils = { path = "crates/utils" }
macros = { path = "crates/macros" }
